config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'categories#index'

  get 'home', to: 'home#index'

  resources :categories do
    resources :cash_flows
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :read, Category, user_id: user.id
      can :create, Category, user_id: user.id
      can :read, CashFlow, author_id: user.id
      can :create, CashFlow, author_id: user.id
    else
      cannot :read, Category
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cash_flow.rb
class CashFlow < ApplicationRecord
  has_many :cash_flow_categories
  has_many :categories, through: :cash_flow_categories

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/cash_flow_category.rb
class CashFlowCategory < ApplicationRecord
  belongs_to :cash_flow
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :cash_flow_categories
  has_many :cash_flows, through: :cash_flow_categories

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true

  has_many :categories
  has_many :cash_flows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to home_path
    end
  end
end

app/controllers/cash_flows_controller.rb
class CashFlowsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @select_option = Category.all
    @category = Category.find(params[:category_id])
    @cash_flow = CashFlow.new
  end

  def create
    @cash_flow = CashFlow.create(cash_flow_params)
    @category = Category.find(params[:category_id])
    @cash_flow.categories << @category
    if @cash_flow.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  private

  def cash_flow_params
    params.require(:cash_flow).permit(:name, :amount, :category_id).merge(author_id: current_user.id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @categories = Category.includes(:cash_flows).order(created_at: :desc).all
  end

  def show
    @category = Category.includes(:cash_flows).find(params[:id])
    @cash_flow = @category.cash_flows.order(created_at: :desc)
    @total_amount = @category.cash_flows.sum(&:amount)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cash_flows_helper.rb
module CashFlowsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cash_flows/new.html.erb
<section class="main-container">
  <div class="headline">
    <%= link_to category_path(@category) do %>
      <div class="arrow">&larr;</div>
    <% end %>
    <h2 class="add-new">ADD TRANSACTION</h2>
  </div>

  <div class="add-form-container">
    <%= form_for [@category, @cash_flow] do |f| %>
      <div>
        <%= f.label "Transaction Name", class: "label" %>
        <%= f.text_field :name, class: "input-field" %>
      </div>

      <div>
        <%= f.label :amount, class: "label" %>
        <%= f.text_field :amount, class: "input-field" %>
      </div>

      <%= f.submit "Add Transaction", class: "form-submit-btn" %>
    <% end %>
  </div>
</section>

app/views/categories/index.html.erb
<section class="main-container">
  <div class="headline">
    <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "log-out" %>
    <h2>CATEGORIES</h2>
    <%= link_to new_category_path do %>
      <div class="arrow">&rarr;</div>
    <% end %>

  </div>

  <div class="categories-container">
    <% @categories.each do |category| %>
      <% if can? :read, category %>
        <div class="category-wrapper">
          <div class="category-icon">
            <img src="<%= category.icon %>" class="icon">
          </div>

          <div class="category-details">
            <%= link_to category.name, category_path(category), class: "category-name" %>
            <p class="category-date"><%= category.created_at.strftime('%Y-%b-%d') %></p>
          </div>

          <div class="total-amount">
            <p>$<%= category.cash_flows.sum(:amount) %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="add-category">
    <%= link_to "ADD NEW CATEGORY", new_category_path, class: "add-btn" %>
  </div>
</section>

app/views/categories/new.html.erb
<section class="main-container">
  <div class="headline">
    <%= link_to categories_path do %>
      <div class="arrow">&larr;</div>
    <% end %>
    <h2 class="add-new">ADD CATEGORY</h2>
  </div>

  <div class="add-form-container">
    <%= form_with model: @category do |f| %>
      <div>
        <%= f.label "Category Name", class: "label" %><br>
        <%= f.text_field :name, placeholder: "Enter Category Name", class: "input-field" %>
      </div>

      <% @icon_options = [
        ['Shopping', 'https://img.icons8.com/?size=50&id=JWv_lqo5fs4F&format=png'],
        ['Traveling', 'https://img.icons8.com/?size=50&id=108778&format=png'],
        ['Technology', 'https://img.icons8.com/?size=50&id=104090&format=png'],
        ['Health and Fitness', 'https://img.icons8.com/?size=50&id=40521&format=png'],
        ['Food and Dining', 'https://img.icons8.com/?size=50&id=118431&format=png'],
        ['Entertainment', 'https://img.icons8.com/?size=50&id=12012&format=png'],
        ['Finance', 'https://img.icons8.com/?size=50&id=13009&format=png'],
        ['Education', 'https://img.icons8.com/?size=50&id=vo1XcGH8QAag&format=png'],
        ['Others', 'https://img.icons8.com/?size=50&id=108779&format=png']
      ] %>

      <%= f.label "Category Type: Select Icon", class: "label" %><br>
      <%= f.select :icon, options_for_select(@icon_options), {}, class: 'input-field icon-options' %>

      <%= f.submit class: "form-submit-btn" %>
    <% end %>
  </div>
</section>

app/views/categories/show.html.erb
<section class="main-container">
  <div class="headline">
    <%= link_to categories_path do %>
      <div class="arrow">&larr;</div>
    <% end %>
    <h2>TRANSACTIONS</h2>
    <%= link_to new_category_cash_flow_path(@category) do %>
      <div class="arrow">&rarr;</div>
    <% end %>
  </div>

  <div class="transaction-container">
    <div class="category-wrapper">
      <div class="category-icon">
        <img src="<%= @category.icon %>" class="icon">
      </div>

      <div class="category-details">
        <%= link_to @category.name, class: "category-name" %>
      </div>
    </div>

    <% @cash_flow.each do |cash_flow| %>
      <div class="transaction-details">
        <p class="name-amount"><%= cash_flow.name %>
          <span>$<%= cash_flow.amount %></span>
        </p>
        <p class="date-time"><%= cash_flow.created_at.strftime('%Y-%b-%d') %>
        at <%= cash_flow.created_at.strftime('%H:%M:%S') %></p>
      </div>
    <% end %>

    <div class="total-transaction">TOTAL TRANSACTION
      <span>$<%= @total_amount %></span>
    </div>
    
  </div>

  <div class="add-category">
    <%= link_to "ADD NEW TRANSACTION", new_category_cash_flow_path(@category), class: "add-btn" %>
  </div>
</section>

app/views/home/index.html.erb
<div class="home-container">
  <h1 class="app-name">Budget Buddy</h1>
  <div class="btn-wrapper">
    <%= link_to "LOG IN", new_user_session_path, class: "login-btn" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "sign-up-btn" %>
    <%#= button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn" %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <h2>Budget App</h2>
  <ul class="nav-list">
    <% if user_signed_in? %>
      <li><%= link_to 'Home', root_path, class: "nav-btn" %></li>
    <% end %>
    <% if user_signed_in? %>
      <li>Transaction</li>
      <li>Category</li>
      <li id="user-tab" class="nav-btn">User</li>
        <ul class="user-info-list" id="user-info">
          <li class = "nav-btn">Logged In with</li>
          <li class = "nav-btn">Name: <%= current_user.name %></li>
          <li class = "nav-btn">Email: <%= current_user.email %></li>
          <li class = "nav-btn"><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn" %></li>
        </ul>
    <% else %>
      <li><%= link_to 'Log in', new_user_session_path, class: "btn" %></li>
      <li><%= link_to 'Sign up', new_user_registration_path, class: "btn" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome to my Budget App!</h1>
<%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn" %>
<p>Logged In with</p>
<p>Email: <%= current_user.email %></p>
<p>Username: <%= current_user.name %></p>